apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: uxp-providerconfigs
  namespace: flux-system
spec:
  dependsOn:
  - name: uxp-providers
    namespace: flux-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: haarchri-spaces-01
  path: ./infrastructure/haarchri-spaces-01/providerconfigs/resources
  timeout: 5m
  prune: true
