apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: uxp-providers
  namespace: flux-system
spec:
  dependsOn:
  - name: universal-crossplane
    namespace: flux-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: haarchri-spaces-01
  path: ./infrastructure/haarchri-spaces-01/providers/resources
  timeout: 5m
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: postbuild-settings
