apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: spaces-controlplanes
  namespace: flux-system
spec:
  dependsOn:
  - name: upbound-spaces
    namespace: flux-system
  - name: upbound-pull-secrets
    namespace: flux-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: haarchri-spaces-01
  path: ./infrastructure/haarchri-spaces-01/spaces-controlplanes/resources
  timeout: 5m
  prune: true
