apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: upbound-spaces
  namespace: flux-system
spec:
  dependsOn:
  - name: aws-load-balancer-controller
    namespace: flux-system
  - name: cert-manager
    namespace: flux-system
  - name: ingress-nginx
    namespace: flux-system
  - name: uxp-providerconfigs
    namespace: flux-system
  - name: uxp-providers
    namespace: flux-system
  - name: upbound-pull-secrets
    namespace: flux-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: haarchri-spaces-01
  path: ./infrastructure/haarchri-spaces-01/upbound-spaces/resources
  timeout: 5m
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: postbuild-settings
