apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: upbound-spaces
  namespace: flux-system
spec:
  type: "oci"
  url: oci://us-west1-docker.pkg.dev/orchestration-build/upbound-environments
  interval: 5m
  secretRef:
    name: upbound-pull-secret