apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: flux-system
  - name: aws-load-balancer-controller
    namespace: flux-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: haarchri-spaces-01
  path: ./infrastructure/haarchri-spaces-01/external-dns/resources
  timeout: 5m
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: postbuild-settings
