apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: haarchri-spaces-01
  path: ./infrastructure/haarchri-spaces-01/cert-manager/resources
  timeout: 5m
  prune: true
