apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: universal-crossplane
  namespace: flux-system
spec:
  releaseName: crossplane
  targetNamespace: upbound-system
  install:
    createNamespace: true
  interval: 10m
  timeout: 8m
  chart:
    spec:
      chart: universal-crossplane
      version: ${uxp_version}
      sourceRef:
        kind: HelmRepository
        name: upbound-stable
        namespace: flux-system
