apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-load-balancer-controller/flux.yaml
  - cert-manager/flux.yaml
  - external-dns/flux.yaml
  - ingress-nginx/flux.yaml
  - providerconfigs/flux.yaml
  - providers/flux.yaml
  - sa-flux-kustomize-controller/flux.yaml
  - spaces-controlplanes/flux.yaml
  - universal-crossplane/flux.yaml
  - upbound-pull-secrets/flux.yaml
  - upbound-spaces/flux.yaml
  # post-build variables
  - postbuild.yaml