apiVersion: v1
kind: ConfigMap
metadata:
  name: postbuild-settings
  namespace: flux-system
data:
  irsa_aws_load_balancer: arn:aws:iam::123456789101:role/aws-loadbalancer-controller
  irsa_external_dns: arn:aws:iam::123456789101:role/external-dns
  irsa_flux_kustomize: arn:aws:iam::123456789101:role/flux-kustomize-controller
  dns_route53: upboundrocks.cloud
  cluster_name: upbound-spaces
  cluster_region: eu-central-1
  external_dns_version: "6.5.6"
  uxp_version: v1.13.2-up.1
  uxp_provider_helm_version: "v0.15.0"
  uxp_provider_kubernetes_version: "v0.9.0"
  spaces_version: "1.0.0"
  spaces_dns_host: upbound-spaces.upboundrocks.cloud
  spaces_upbound_account: upbound
