apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: upbound-pull-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: sa-flux-kustomize-controller
    namespace: flux-system
  interval: 5m
  decryption:
    provider: sops
  sourceRef:
    kind: GitRepository
    name: haarchri-spaces-01
  path: ./infrastructure/haarchri-spaces-01/upbound-pull-secrets/resources
  timeout: 5m
  prune: true
